import { UserProfile } from "@/components/profile/user-profile";
import { User } from "@/lib/data/users";
import type { Metadata } from "next";

interface ProfilePageProps {
  params: {
    username: string;
  };
}
const user: User = {
  id: "1",
  username: "alexjohnson",
  name: "Alex Johnson",
  avatar: "/avatars/alex.png",
  bio: "Quiz enthusiast and knowledge seeker. I love challenging myself with difficult quizzes!",
  level: 42,
  score: 9850,
  quizzesTaken: 187,
  quizzesCreated: 15,
  badge: "Diamond",
  country: "United States",
  joinedDate: "2022-03-15",
  isVerified: true,
  followers: 1243,
  following: 356,
  achievements: [
    {
      id: "a1",
      name: "Quiz Master",
      description: "Complete 100 quizzes with a score of 80% or higher",
      icon: "trophy",
      earnedAt: "2023-01-20",
      rarity: "epic",
    },
    {
      id: "a2",
      name: "Knowledge Seeker",
      description: "Complete quizzes in 10 different categories",
      icon: "search",
      earnedAt: "2022-11-05",
      rarity: "uncommon",
    },
    {
      id: "a3",
      name: "Perfect Score",
      description: "Achieve 100% on a difficult quiz",
      icon: "star",
      earnedAt: "2023-04-12",
      rarity: "rare",
    },
  ],
  recentActivity: [
    {
      id: "act1",
      type: "quiz_completed",
      content: "Completed 'World History Trivia' with a score of 95%",
      timestamp: "2023-05-01T14:30:00Z",
      relatedId: "q123",
      relatedName: "World History Trivia",
    },
    {
      id: "act2",
      type: "achievement_earned",
      content: "Earned the 'Quiz Wizard' achievement",
      timestamp: "2023-04-28T09:15:00Z",
      relatedId: "a7",
      relatedName: "Quiz Wizard",
    },
    {
      id: "act3",
      type: "level_up",
      content: "Reached level 42",
      timestamp: "2023-04-25T16:45:00Z",
    },
  ],
  quizHistory: [
    {
      id: "qh1",
      quizId: "q123",
      quizName: "World History Trivia",
      score: 95,
      maxScore: 100,
      completedAt: "2023-05-01T14:30:00Z",
      timeSpent: 720,
      category: "History",
      difficulty: "hard",
    },
    {
      id: "qh2",
      quizId: "q456",
      quizName: "Science Facts",
      score: 88,
      maxScore: 100,
      completedAt: "2023-04-29T10:20:00Z",
      timeSpent: 540,
      category: "Science",
      difficulty: "medium",
    },
    {
      id: "qh3",
      quizId: "q789",
      quizName: "Pop Culture Quiz",
      score: 75,
      maxScore: 100,
      completedAt: "2023-04-27T19:10:00Z",
      timeSpent: 480,
      category: "Entertainment",
      difficulty: "easy",
    },
  ],
  stats: {
    averageScore: 87.5,
    bestCategory: "History",
    totalTimePlayed: 42600,
    winRate: 0.78,
    highestStreak: 12,
    currentStreak: 5,
    favoriteCategory: "Science",
    weakestCategory: "Sports",
    quizCompletionRate: 0.94,
  },
  createdQuizzes: [
    {
      id: "q1",
      title: "World Geography Challenge",
      description: "Test your knowledge of world geography with this challenging quiz!",
      image: "/world-map-quiz.png",
      category: "Geography",
      difficulty: "medium",
      questions: 20,
      plays: 1245,
      averageScore: 76,
      rating: 4.7,
      createdAt: "2023-01-15T10:30:00Z",
      updatedAt: "2023-02-10T14:20:00Z",
      published: true,
      featured: true,
      isTournament: false,
      stats: {
        completionRate: 87,
        averageTimeSpent: 840,
        mostMissedQuestion: 12,
        highestScore: 100,
        lowestScore: 35,
      },
    },
    {
      id: "q2",
      title: "Science Quiz Extravaganza",
      description: "From physics to biology, test your science knowledge!",
      image: "/space-exploration-quiz.png",
      category: "Science",
      difficulty: "hard",
      questions: 25,
      plays: 876,
      averageScore: 68,
      rating: 4.5,
      createdAt: "2023-02-20T09:15:00Z",
      updatedAt: "2023-02-20T09:15:00Z",
      published: true,
      featured: false,
      isTournament: false,
      stats: {
        completionRate: 72,
        averageTimeSpent: 1200,
        mostMissedQuestion: 18,
        highestScore: 96,
        lowestScore: 28,
      },
    },
    {
      id: "q3",
      title: "History Through the Ages",
      description: "Journey through time with this comprehensive history quiz!",
      image: "/ancient-civilizations-quiz.png",
      category: "History",
      difficulty: "medium",
      questions: 30,
      plays: 1532,
      averageScore: 72,
      rating: 4.8,
      createdAt: "2023-03-05T11:45:00Z",
      updatedAt: "2023-04-10T16:30:00Z",
      published: true,
      featured: true,
      isTournament: false,
      stats: {
        completionRate: 85,
        averageTimeSpent: 1500,
        mostMissedQuestion: 22,
        highestScore: 100,
        lowestScore: 40,
      },
    },
    {
      id: "q4",
      title: "Pop Culture Trivia",
      description: "Test your knowledge of movies, music, and celebrities!",
      image: "/space-exploration-quiz.png",
      category: "Entertainment",
      difficulty: "easy",
      questions: 15,
      plays: 2145,
      averageScore: 84,
      rating: 4.6,
      createdAt: "2023-03-18T14:20:00Z",
      updatedAt: "2023-03-18T14:20:00Z",
      published: true,
      featured: false,
      isTournament: false,
      stats: {
        completionRate: 94,
        averageTimeSpent: 600,
        mostMissedQuestion: 10,
        highestScore: 100,
        lowestScore: 53,
      },
    },
    {
      id: "q5",
      title: "Annual Science Tournament",
      description: "Compete with others in this annual science knowledge tournament!",
      image: "/technology-quiz.png",
      category: "Science",
      difficulty: "hard",
      questions: 40,
      plays: 567,
      averageScore: 62,
      rating: 4.9,
      createdAt: "2023-04-01T08:30:00Z",
      updatedAt: "2023-04-15T10:45:00Z",
      published: true,
      featured: true,
      isTournament: true,
      tournamentDetails: {
        startDate: "2023-05-01T00:00:00Z",
        endDate: "2023-05-31T23:59:59Z",
        participants: 324,
        prize: "$500 Amazon Gift Card",
        status: "active",
      },
      stats: {
        completionRate: 68,
        averageTimeSpent: 2400,
        mostMissedQuestion: 35,
        highestScore: 98,
        lowestScore: 22,
      },
    },
  ],
};
export async function generateMetadata({ params }: ProfilePageProps): Promise<Metadata> {
  if (!user) {
    return {
      title: "User Not Found | QuizHub",
      description: "This user profile could not be found.",
    };
  }

  return {
    title: `${user.name}'s Profile | QuizHub`,
    description: `Check out ${user.name}'s quiz achievements, stats, and more.`,
  };
}

export default async function ProfilePage() {
  return <UserProfile user={user} />;
}
